plugins {
    id 'org.jetbrains.kotlin.plugin.spring'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':gateway:autoconfigure')
    implementation project(':support:logging')
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // Test dependencies (if any tests remain in core/gateway)
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
}
