plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.2.21'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'cc.midolog.examples'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll '-Xjsr305=strict', '-Xannotation-default-target=param-property'
    }
}

repositories {
    def localRepoDir = project.findProperty('backendInitRepo') ?
        file(project.property('backendInitRepo')) :
        file("$rootDir/../../build/repo")
    maven {
        url = localRepoDir.toURI()
    }
    mavenCentral()
    maven { url = 'https://repo.spring.io/milestone' }
}

dependencies {
    implementation(platform("cc.midolog:backend-init-bom:0.0.1-SNAPSHOT"))

    implementation("cc.midolog:backend-init-domain")
    implementation("cc.midolog:backend-init-support-web")
    runtimeOnly("cc.midolog:backend-init-storage-jpa")

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-reactor'
    implementation 'tools.jackson.module:jackson-module-kotlin'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'com.h2database:h2'
}

tasks.named('test') {
    useJUnitPlatform()
}
