plugins {
    id 'cc.midolog.publishing'
    id 'org.jetbrains.kotlin.plugin.spring'
    id 'io.spring.dependency-management'
    id 'cc.midolog.jpa-dsl'
}

apply from: rootProject.file('gradle/domain-entities.gradle')

mybatisDynamicSql {
    configureDomainEntities(it)
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add('-Xjspecify-annotations=ignore')
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.6"
    }
}

dependencies {
    implementation project(':core:domain')
    implementation project(':support:util')

    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.1'
    implementation 'org.mybatis.dynamic-sql:mybatis-dynamic-sql:2.0.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'tools.jackson.module:jackson-module-kotlin'

    testImplementation testFixtures(project(':core:domain'))
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:4.0.1'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2'
}
