plugins {
    id 'org.jetbrains.kotlin.plugin.spring'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.6"
    }
}

dependencies {
    implementation project(':core:domain')
    implementation project(':support:util')

    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'tools.jackson.module:jackson-module-kotlin'

    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:4.0.1'
}
