rootProject.name = 'backend-init'

includeBuild 'build-logic'

// core
include 'core:application'
include 'core:batch'
include 'core:gateway'
include 'gateway:core'
include 'gateway:autoconfigure'
include 'core:domain'

// client
include 'client:storage-file'

// storage
include 'storage:mybatis'
include 'storage:jpa'

// support
include 'support:util'
include 'support:logging'
include 'support:web'
include 'support:jwt'
