plugins {
    id 'cc.midolog.publishing'
    id 'org.jetbrains.kotlin.jvm'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.6"
    }
}

dependencies {
    api project(':storage:file-autoconfigure')
    api project(':storage:file-s3')
}
