plugins {
    id 'cc.midolog.publishing'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.6"
    }
}

dependencies {
    implementation project(':support:util')

    implementation 'ch.qos.logback:logback-classic'
    implementation 'io.projectreactor:reactor-core'
    implementation 'net.logstash.logback:logstash-logback-encoder:8.0'

    testImplementation 'io.projectreactor:reactor-test'
}
