plugins {
    id 'org.jetbrains.kotlin.plugin.spring'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':core:domain')
    implementation project(':support:util')
    implementation project(':support:logging')
    implementation project(':support:web')
    implementation project(':gateway:starter')

    runtimeOnly project(':client:storage-file')
    runtimeOnly project(':storage:mybatis')
    runtimeOnly project(':storage:jpa')
    runtimeOnly project(':storage:file-local')
    if (project.hasProperty('customer')) {
        runtimeOnly project(":customers:${project.property('customer')}")
    }

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'io.projectreactor.kotlin:reactor-kotlin-extensions'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-reactor'
    implementation 'tools.jackson.module:jackson-module-kotlin'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation project(':support:jwt')


    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly project(':storage:mybatis')
    testRuntimeOnly project(':storage:jpa')
    testRuntimeOnly "com.h2database:h2"
}
