plugins {
    id 'java-platform'
    id 'cc.midolog.publishing'
}

javaPlatform {
    allowDependencies()
}

rootProject.subprojects.each { Project sp ->
    if (sp != project) {
        sp.plugins.withId('cc.midolog.publishing') {
            dependencies.constraints.add('api', sp)
        }
    }
}
