plugins {
    id 'java-library'
    id 'cc.midolog.publishing'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.6"
    }
}

dependencies {
    api project(':gateway:core')
    api project(':gateway:autoconfigure')
    api 'org.springframework.boot:spring-boot-starter-webflux'
    api 'org.springframework.boot:spring-boot-starter-data-redis-reactive'
}
